/**
 * @author              Young Midoria
 * @name                HeroAcademia Authorization
 * @module              heroacademia_authorization.js
 * @kind                Config
 * @copyright           June 2019 HeroAcademia Authorization
 */

module.exports = {
    serviceName             : 'HeroAcademia Authorization',
    serviceDescription      : `Generated by Midoria : ${new Date().getFullYear()}. Authorization service`,
    author                  : 'Young Midoria',
    copyright               : `Copyright : ${new Date().getFullYear()}`,
    repoURL                 : "http://github.com",
    licence                 : 'MIT', // The MIT License
    version                 : '0.0.1', // First alpha release
    baseURL                 : '/auth',
    environment             : {
        DEBUG                   : "*",
        PORT                    : 3400,
        MONGODB_URL             : "mongodb://localhost:27017/auth",
        REVERSE_PROXY           : "http://localhost",
        COLLECTION_RETURN_SIZE  : "12",
        ELASTIC_SEARCH_URL      : "http://localhost:9200",
        TOKEN_EXPIRATION_TIME   : "60d",
        LOG_STASH_PORT          : 5000,
        SECRET                  : "changeMeNow"
    },
    docker                  : true,
    jenkins                 : true,
    postman                 : true,
    useProxy                : false,
    test                    : true,
    documentation           : true,
    readMe                  : true,
    instance                : 0,
    commit                  : true,
    runServer               : true,
    commitMessage           : 'Initial commit for hero academia.'

};