version: '2'
services:

  #################################################################################################################################
  ########################                     __serviceName__              #####################################################
  #################################################################################################################################

    __serviceName__:
      build: ./.
      ports:
        - "__port__:__port__"
      restart: always
      environment:
        - HTTP_PORT=__port__
        - MONGODB_URL=__mongodbURL__
        - MONGODB_URL_TEST=__mongodbURLTest__
        - COLLECTION_RETURN_SIZE=__collectionReturnSize__
        - REVERSE_PROXY=__reverseProxy__
        - ELASTIC_SEARCH_URL=__elasticSearch__
        - LOG_STASH_PORT=__logStashPort__
        - DEBUG=*
        - TOKEN_EXPIRATION_TIME=__tokenExpiration__
        - SECRET=__secret__
        - SALT_LENGTH=__saltLength__
        - USER_NAME=gennode
        - PASSWORD=changeMeNowAndQuick
      depends_on:
        - __serviceName___db
    # Defining __serviceName__ DB
    __serviceName___db:
       image: mongo:latest
       restart: always
       volumes:
         - .:/data/db

  #################################################################################################################################
  #################################################################################################################################